[package]
name = "git-toolkit"
description = "TODO: Library description"
categories = ["command-line-utilities", "development-tools"]
keywords.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
exclude.workspace = true
include.workspace = true
publish = true

[dependencies]
